//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopMoth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prace()
        {
            this.Autorzy = new HashSet<Autorzy>();
            this.Kategorie = new HashSet<Kategorie>();
        }
    
        public int id_pracy { get; set; }
        public string tytul { get; set; }
        public string jezyk { get; set; }
        public string rodzaj { get; set; }
        public Nullable<int> rok_publikacji { get; set; }
        public string slowa_kluczowe { get; set; }
        public Nullable<int> id_wydawcy { get; set; }
    
        public virtual Wydawcy Wydawcy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorzy> Autorzy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategorie> Kategorie { get; set; }
    }
}
