#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspsql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="banach")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertoddzialy(oddzialy instance);
    partial void Updateoddzialy(oddzialy instance);
    partial void Deleteoddzialy(oddzialy instance);
    partial void Insertpracownicy(pracownicy instance);
    partial void Updatepracownicy(pracownicy instance);
    partial void Deletepracownicy(pracownicy instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["banachConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<oddzialy> oddzialies
		{
			get
			{
				return this.GetTable<oddzialy>();
			}
		}
		
		public System.Data.Linq.Table<pracownicy> pracownicies
		{
			get
			{
				return this.GetTable<pracownicy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oddzialy")]
	public partial class oddzialy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _oddzial;
		
		private string _nazwa;
		
		private string _lokalizacja;
		
		private EntitySet<pracownicy> _pracownicies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnoddzialChanging(int value);
    partial void OnoddzialChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OnlokalizacjaChanging(string value);
    partial void OnlokalizacjaChanged();
    #endregion
		
		public oddzialy()
		{
			this._pracownicies = new EntitySet<pracownicy>(new Action<pracownicy>(this.attach_pracownicies), new Action<pracownicy>(this.detach_pracownicies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oddzial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int oddzial
		{
			get
			{
				return this._oddzial;
			}
			set
			{
				if ((this._oddzial != value))
				{
					this.OnoddzialChanging(value);
					this.SendPropertyChanging();
					this._oddzial = value;
					this.SendPropertyChanged("oddzial");
					this.OnoddzialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(255)")]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lokalizacja", DbType="VarChar(255)")]
		public string lokalizacja
		{
			get
			{
				return this._lokalizacja;
			}
			set
			{
				if ((this._lokalizacja != value))
				{
					this.OnlokalizacjaChanging(value);
					this.SendPropertyChanging();
					this._lokalizacja = value;
					this.SendPropertyChanged("lokalizacja");
					this.OnlokalizacjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oddzialy_pracownicy", Storage="_pracownicies", ThisKey="oddzial", OtherKey="oddzial")]
		public EntitySet<pracownicy> pracownicies
		{
			get
			{
				return this._pracownicies;
			}
			set
			{
				this._pracownicies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pracownicies(pracownicy entity)
		{
			this.SendPropertyChanging();
			entity.oddzialy = this;
		}
		
		private void detach_pracownicies(pracownicy entity)
		{
			this.SendPropertyChanging();
			entity.oddzialy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pracownicy")]
	public partial class pracownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nazwisko;
		
		private string _praca;
		
		private System.Nullable<int> _kierownik;
		
		private System.Nullable<System.DateTime> _data_zatrudnienia;
		
		private System.Nullable<decimal> _wynagrodzenie;
		
		private System.Nullable<decimal> _prowizja;
		
		private int _oddzial;
		
		private EntitySet<pracownicy> _pracownicies;
		
		private EntityRef<pracownicy> _pracownicy1;
		
		private EntityRef<oddzialy> _oddzialy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void OnpracaChanging(string value);
    partial void OnpracaChanged();
    partial void OnkierownikChanging(System.Nullable<int> value);
    partial void OnkierownikChanged();
    partial void Ondata_zatrudnieniaChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_zatrudnieniaChanged();
    partial void OnwynagrodzenieChanging(System.Nullable<decimal> value);
    partial void OnwynagrodzenieChanged();
    partial void OnprowizjaChanging(System.Nullable<decimal> value);
    partial void OnprowizjaChanged();
    partial void OnoddzialChanging(int value);
    partial void OnoddzialChanged();
    #endregion
		
		public pracownicy()
		{
			this._pracownicies = new EntitySet<pracownicy>(new Action<pracownicy>(this.attach_pracownicies), new Action<pracownicy>(this.detach_pracownicies));
			this._pracownicy1 = default(EntityRef<pracownicy>);
			this._oddzialy = default(EntityRef<oddzialy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_praca", DbType="VarChar(255)")]
		public string praca
		{
			get
			{
				return this._praca;
			}
			set
			{
				if ((this._praca != value))
				{
					this.OnpracaChanging(value);
					this.SendPropertyChanging();
					this._praca = value;
					this.SendPropertyChanged("praca");
					this.OnpracaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kierownik", DbType="Int")]
		public System.Nullable<int> kierownik
		{
			get
			{
				return this._kierownik;
			}
			set
			{
				if ((this._kierownik != value))
				{
					if (this._pracownicy1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkierownikChanging(value);
					this.SendPropertyChanging();
					this._kierownik = value;
					this.SendPropertyChanged("kierownik");
					this.OnkierownikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zatrudnienia", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_zatrudnienia
		{
			get
			{
				return this._data_zatrudnienia;
			}
			set
			{
				if ((this._data_zatrudnienia != value))
				{
					this.Ondata_zatrudnieniaChanging(value);
					this.SendPropertyChanging();
					this._data_zatrudnienia = value;
					this.SendPropertyChanged("data_zatrudnienia");
					this.Ondata_zatrudnieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wynagrodzenie", DbType="Money")]
		public System.Nullable<decimal> wynagrodzenie
		{
			get
			{
				return this._wynagrodzenie;
			}
			set
			{
				if ((this._wynagrodzenie != value))
				{
					this.OnwynagrodzenieChanging(value);
					this.SendPropertyChanging();
					this._wynagrodzenie = value;
					this.SendPropertyChanged("wynagrodzenie");
					this.OnwynagrodzenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prowizja", DbType="Money")]
		public System.Nullable<decimal> prowizja
		{
			get
			{
				return this._prowizja;
			}
			set
			{
				if ((this._prowizja != value))
				{
					this.OnprowizjaChanging(value);
					this.SendPropertyChanging();
					this._prowizja = value;
					this.SendPropertyChanged("prowizja");
					this.OnprowizjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oddzial", DbType="Int NOT NULL")]
		public int oddzial
		{
			get
			{
				return this._oddzial;
			}
			set
			{
				if ((this._oddzial != value))
				{
					if (this._oddzialy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnoddzialChanging(value);
					this.SendPropertyChanging();
					this._oddzial = value;
					this.SendPropertyChanged("oddzial");
					this.OnoddzialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pracownicy_pracownicy", Storage="_pracownicies", ThisKey="id", OtherKey="kierownik")]
		public EntitySet<pracownicy> pracownicies
		{
			get
			{
				return this._pracownicies;
			}
			set
			{
				this._pracownicies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pracownicy_pracownicy", Storage="_pracownicy1", ThisKey="kierownik", OtherKey="id", IsForeignKey=true)]
		public pracownicy pracownicy1
		{
			get
			{
				return this._pracownicy1.Entity;
			}
			set
			{
				pracownicy previousValue = this._pracownicy1.Entity;
				if (((previousValue != value) 
							|| (this._pracownicy1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pracownicy1.Entity = null;
						previousValue.pracownicies.Remove(this);
					}
					this._pracownicy1.Entity = value;
					if ((value != null))
					{
						value.pracownicies.Add(this);
						this._kierownik = value.id;
					}
					else
					{
						this._kierownik = default(Nullable<int>);
					}
					this.SendPropertyChanged("pracownicy1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oddzialy_pracownicy", Storage="_oddzialy", ThisKey="oddzial", OtherKey="oddzial", IsForeignKey=true)]
		public oddzialy oddzialy
		{
			get
			{
				return this._oddzialy.Entity;
			}
			set
			{
				oddzialy previousValue = this._oddzialy.Entity;
				if (((previousValue != value) 
							|| (this._oddzialy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oddzialy.Entity = null;
						previousValue.pracownicies.Remove(this);
					}
					this._oddzialy.Entity = value;
					if ((value != null))
					{
						value.pracownicies.Add(this);
						this._oddzial = value.oddzial;
					}
					else
					{
						this._oddzial = default(int);
					}
					this.SendPropertyChanged("oddzialy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pracownicies(pracownicy entity)
		{
			this.SendPropertyChanging();
			entity.pracownicy1 = this;
		}
		
		private void detach_pracownicies(pracownicy entity)
		{
			this.SendPropertyChanging();
			entity.pracownicy1 = null;
		}
	}
}
#pragma warning restore 1591
