<?xml version="1.0" encoding="utf-8"?><Database Name="banach" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-SBHETR7;Initial Catalog=banach;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="banachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.oddzialy" Member="oddzialies">
    <Type Name="oddzialy">
      <Column Name="oddzial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="lokalizacja" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="oddzialy_pracownicy" Member="pracownicies" ThisKey="oddzial" OtherKey="oddzial" Type="pracownicy" />
    </Type>
  </Table>
  <Table Name="dbo.pracownicy" Member="pracownicies">
    <Type Name="pracownicy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="praca" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="kierownik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="data_zatrudnienia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="wynagrodzenie" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="prowizja" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="oddzial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="pracownicy_pracownicy" Member="pracownicies" ThisKey="id" OtherKey="kierownik" Type="pracownicy" />
      <Association Name="pracownicy_pracownicy" Member="pracownicy1" ThisKey="kierownik" OtherKey="id" Type="pracownicy" IsForeignKey="true" />
      <Association Name="oddzialy_pracownicy" Member="oddzialy" ThisKey="oddzial" OtherKey="oddzial" Type="oddzialy" IsForeignKey="true" />
    </Type>
  </Table>
</Database>